# Generated by Django 5.1.6 on 2025-03-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfund_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='googledrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.IntegerField(unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enfund_view.user')),
            ],
        ),
    ]
