# Generated by Django 5.1.6 on 2025-03-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfund_view', '0002_googledrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrive',
            name='drive_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
