# Generated by Django 5.1.6 on 2025-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfund_view', '0003_alter_googledrive_drive_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
